### PR TITLE
Modernize build system for the Hy lang Sphinx domain

### PR DESCRIPTION
**Pull request by wrobell**
Move build system configuration to setup.cfg and pyproject.toml files.

Keep dependencies in one place (this is setup.cfg, no need for requirements files anymore). For example Sphinx version was different in setup.py and requirements text files. Drop some strict dependencies for pip and wheel.

Also, remove function for Python 3.6 from `hy_documenters` module as Hy lang requires Python 3.8 or later.

### CODE REVIEW

**Comment by wrobell** [comment]
Tested with
```
python -m build
```

And then by building Hylang documentation. I am getting some warnings, not sure if they were there before.

The Hylang domain module seems quite out of date, and it really needs more work. Please treat this pull request as first step of many.

**Comment by Kodiologist** [comment]
> The Hylang domain module seems quite out of date, and it really needs more work.

I know. Nobody's really maintaining it, so little happens.

**Comment by wrobell** [comment]
> > The Hylang domain module seems quite out of date, and it really needs more work.
> 
> I know. Nobody's really maintaining it, so little happens.

It is not my intention to criticise. Just explaining myself why this pull request first.

**Comment by scauligi** [comment]
I'm not really sure how you're testing it? `python -m build` is a command to run a module called "build", which doesn't exist here or in hy.

I tried the following (MacOS, python 3.11.4), but wasn't able to get the docs to build:
```bash
# in a fresh directory
$ python3 -m venv --upgrade-deps venv
$ git clone https://github.com/hylang/hy.git
$ git clone https://github.com/wrobell/sphinxcontrib-hydomain.git -b build-modernize
$ cd sphinxcontrib-hydomain
$ pip install .  # installs Sphinx 7.1.2
$ cd ../hy/docs
$ sphinx-build . _build -b html
ModuleNotFoundError: No module name 'sphinx_rtd_theme'

$ pip install sphinx-rtd-theme  # Note: this downgrades Sphinx to 6.2.1
$ sphinx-build . _build -b html
NotImplementedError

$ cd ../../sphinxcontrib-hydomain
$ pip install -U . --upgrade-strategy=eager  # reinstall Sphinx 7.1.2
$ pip install -U --pre sphinx-rtd-theme  # latest alpha uses Sphinx 7, so no downgrade
$ cd ../hy/docs
$ sphinx-build . _build -b html
cannot import name 'parse' from 'sphinx.pycode.ast'
```

Do you have other pending modifications to get sphinxcontrib-hydomain working with Sphinx 7?

**Comment by wrobell** [comment]
> I'm not really sure how you're testing it? `python -m build` is a command to run a module called "build", which doesn't exist here or in hy.

- https://pypi.org/project/build/
- https://pypa-build.readthedocs.io/en/latest/

You probably can use any other compatible builder. This one comes from Python Packaging Authority, so I am using it.

[...]

> Do you have other pending modifications to get sphinxcontrib-hydomain working with Sphinx 7?
Not at the moment. Hy requires Sphinx 5.0.2 (based on requirements-dev.txt), so I used that.

In next pull requests I will try to upgrade to Sphinx 6 or Sphinx 7 (depends on what sphinx_rtd_theme will require, not sure what changed in last couple of weeks).

**Comment by scauligi** [comment]
aha, I thought you were updating the required Sphinx version alongside upgrading the build system, my bad

**Comment by Kodiologist** [comment]
I don't think I can really take on the responsibility of reviewing PRs for this repository. Sorry.

**Comment by Kodiologist** [comment]
To be clear, Hy and Hyrule's merge policy doesn't apply to this repository. It's the wild west here. So, Sunjay, if you like, you can decide what PRs to merge, or you could reasonably give wrobell push permissions, since he seems interested in doing some serious work here.

**Comment by wrobell** [comment]
@scauligi Thanks for the CI build. Not sure why it was run so late though.

**Pull request merged**
