### PR TITLE
Clean code of `_pseudo_parse_arglist` function

### PR DESCRIPTION
**Pull request by wrobell**
There is no need for the whole implicit try/except machinery.

### CODE REVIEW

**Comment by scauligi** [comment]
Dope! Since it looks like you're going to be doing a bunch more on this, do you want push access directly to the repo?

**Comment by wrobell** [comment]
You can give me the access, but I will still create the pull requests for review. :)

**Comment by scauligi** [comment]
Ah looks like I don't have admin permissions for this repo; @Kodiologist can you update my and/or wrobell's permissions?

**Comment by Kodiologist** [comment]
Done.

**Comment by wrobell** [comment]
Damn it. I was too late with other changes :)

**Comment by Kodiologist** [comment]
@wrobell @scauligi Could you update LICENSE to add yourselves as authors, with your legal names?

**Pull request merged**
